version: 2.1

orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  print_hello:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - run: echo hello
  print_world:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - run: echo world

  printname:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "echos my name"
          command: |
            echo $MY_ENV_NAME      
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - print_hello
      - print_world:
          requires:
            - print_hello